version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ConnectionStrings__DefaultConnection: "Host=db;Database=studybuddy;Username=studybuddy;Password=studybuddypassword"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: studybuddy
      POSTGRES_PASSWORD: studybuddypassword
      POSTGRES_DB: studybuddy
