services:
  studybuddy:
    image: studybuddy
    build:
      context: .
      dockerfile: StudyBuddy/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - studybuddy.api

  studybuddy.api:
    image: studybuddy.api
    build:
      context: .
      dockerfile: StudyBuddy.API/Dockerfile
    ports:
      - "8100:80"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: "http://*:80"

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: studybuddy

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    env_file:
      - .env
