version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      ASPNETCORE_URLS: "http://*:80"

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: studybuddy

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    env_file:
      - .env
